// Node Templates //
export const UPDATE_NODE_TEMPLATE = "UPDATE_NODE_TEMPLATE";
export const SUBMIT_NODE_TEMPLATE = "SUBMIT_NODE_TEMPLATE";
export const INITIALIZE_NODE_TEMPLATE = "INITIALIZE_NODE_TEMPLATE";
export const UPDATE_NODE = "UPDATE_NODE";
export const ADD_PROPERTY = "ADD_PROPERTY";
export const SET_PROPERTY = "SET_PROPERTY";
export const RENAME_PROPERTY = "RENAME_PROPERTY";
export const REMOVE_PROPERTY = "REMOVE_PROPERTY";
export const UPDATE_NODES = "UPDATE_NODES";

//////////////////////
// NETWORK REQUESTS //
//////////////////////

// Node Templates //
export const GET_ALL_TEMPLATES = "GET_ALL_TEMPLATES";
export const SEARCH_TEMPLATES = "SEARCH_TEMPLATES";
export const RECEIVE_TEMPLATES = "RECEIVE_TEMPLATES";
export const GET_TEMPLATE = "GET_TEMPLATE";
export const PUT_TEMPLATE = "PUT_TEMPLATE";
export const POST_TEMPLATE = "POST_TEMPLATE";
export const DELETE_TEMPLATE = "DELETE_TEMPLATE";
export const RECEIVE_TEMPLATE = "RECEIVE_TEMPLATE";

// Relationship Templates //
export const UPDATE_RELATIONSHIP_TEMPLATE = "UPDATE_RELATIONSHIP_TEMPLATE";
export const GET_RELATIONSHIP_TEMPLATE = "GET_RELATIONSHIP_TEMPLATE";
export const PUT_RELATIONSHIP_TEMPLATE = "PUT_RELATIONSHIP_TEMPLATE";
export const POST_RELATIONSHIP_TEMPLATE = "POST_RELATIONSHIP_TEMPLATE";
export const DELETE_RELATIONSHIP_TEMPLATE = "DELETE_RELATIONSHIP_TEMPLATE";
export const RECEIVE_RELATIONSHIP_TEMPLATE = "RECEIVE_RELATIONSHIP_TEMPLATE";
export const RECEIVE_RELATIONSHIP_TEMPLATES = "RECEIVE_RELATIONSHIP_TEMPLATES";

// Nodes //
export const GET_ALL_NODES = "GET_ALL_NODES";
export const SEARCH_NODES = "SEARCH_NODES";
export const RECEIVE_NODES = "RECEIVE_NODES";
export const GET_NODE = "GET_NODE";
export const PUT_NODE = "PUT_NODE";
export const POST_NODE = "POST_NODE";
export const DELETE_NODE = "DELETE_NODE";
export const RECEIVE_NODE = "RECEIVE_NODE";

// Relationships //
export const UPDATE_RELATIONSHIP = "UPDATE_RELATIONSHIP";
export const UPDATE_RELATIONSHIPS = "UPDATE_RELATIONSHIPS";
export const GET_RELATIONSHIP = "GET_RELATIONSHIP";
export const PUT_RELATIONSHIP = "PUT_RELATIONSHIP";
export const POST_RELATIONSHIP = "POST_RELATIONSHIP";
export const DELETE_RELATIONSHIP = "DELETE_RELATIONSHIP";
export const RECEIVE_RELATIONSHIP = "RECEIVE_RELATIONSHIP";
export const RECEIVE_RELATIONSHIPS = "RECEIVE_RELATIONSHIPS";

// Error Handling //
export const TEMPLATE_REQUEST_ERROR = "TEMPLATE_REQUEST_ERROR";
export const TEMPLATES_REQUEST_ERROR = "TEMPLATES_REQUEST_ERROR";
export const NODE_REQUEST_ERROR = "NODE_REQUEST_ERROR";
export const NODES_REQUEST_ERROR = "NODES_REQUEST_ERROR";
export const RELATIONSHIP_REQUEST_ERROR = "RELATIONSHIP_REQUEST_ERROR";
export const RELATIONSHIPS_REQUEST_ERROR = "RELATIONSHIPS_REQUEST_ERROR";
