export const UPDATE_NODE_TEMPLATE = "UPDATE_NODE_TEMPLATE";
export const SUBMIT_NODE_TEMPLATE = "SUBMIT_NODE_TEMPLATE";
export const INITIALIZE_NODE_TEMPLATE = "INITIALIZE_NODE_TEMPLATE";
export const UPDATE_NODE = "UPDATE_NODE";
export const ADD_PROPERTY = "ADD_PROPERTY";
export const SET_PROPERTY = "SET_PROPERTY";
export const RENAME_PROPERTY = "RENAME_PROPERTY";
export const REMOVE_PROPERTY = "REMOVE_PROPERTY";
export const UPDATE_NODES = "UPDATE_NODES";

//////////////////////
// NETWORK REQUESTS //
//////////////////////

// Templates //
export const GET_ALL_TEMPLATES = "GET_ALL_TEMPLATES";
export const SEARCH_TEMPLATES = "SEARCH_TEMPLATES";
export const RECEIVE_TEMPLATES = "RECEIVE_TEMPLATES";
export const GET_TEMPLATE = "GET_TEMPLATE";
export const PUT_TEMPLATE = "PUT_TEMPLATE";
export const POST_TEMPLATE = "POST_TEMPLATE";
export const DELETE_TEMPLATE = "DELETE_TEMPLATE";
export const RECEIVE_TEMPLATE = "RECEIVE_TEMPLATE";

// Nodes //
export const SEARCH_NODES = "SEARCH_NODES";
export const GET_NODE = "GET_NODE";
export const PUT_NODE = "PUT_NODE";
export const POST_NODE = "POST_NODE";
export const DELETE_NODE = "DELETE_NODE";