export const UPDATE_NODE = "UPDATE_NODE";
export const ADD_PROPERTY = "ADD_PROPERTY";
export const SET_PROPERTY = "SET_PROPERTY";
export const RENAME_PROPERTY = "RENAME_PROPERTY";
export const REMOVE_PROPERTY = "REMOVE_PROPERTY";
